-- MySQL Script generated by MySQL Workbench
-- 05/18/16 15:06:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema test_pds
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test_pds
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test_pds` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `test_pds` ;

-- -----------------------------------------------------
-- Table `test_pds`.`Agency`
-- -----------------------------------------------------

drop table IF EXISTS Staff;
drop table IF EXISTS Account;
drop table IF EXISTS History;
drop table IF EXISTS Loan;
drop table IF EXISTS Loantype;
drop table IF EXISTS Simulation;
drop table IF EXISTS User;
drop table IF EXISTS Insurance;
drop table IF EXISTS Consumer;
drop table IF EXISTS Agency;
drop table IF EXISTS refund;
drop table IF EXISTS Status;


CREATE TABLE IF NOT EXISTS `test_pds`.`Agency` (
  `id_Agency` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Agency`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_pds`.`Consumer`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `test_pds`.`Consumer` (
  `id_Consumer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(1) NOT NULL,
  `dateOfBirth` DATE NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `postCode` VARCHAR(5) NOT NULL,
  `country` VARCHAR(45) NULL,
  `phoneNumber` VARCHAR(10) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `id_Agency` INT NOT NULL,
  `nationality` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Consumer`, `id_Agency`),
  INDEX `fk_Consumers_Agency1_idx` (`id_Agency` ASC),
  CONSTRAINT `fk_Consumers_Agency1`
    FOREIGN KEY (`id_Agency`)
    REFERENCES `test_pds`.`Agency` (`id_Agency`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_pds`.`Account`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `test_pds`.`Account` (
  `id_account` INT NOT NULL AUTO_INCREMENT,
  `capital` VARCHAR(45) NOT NULL,
  `id_Consumer` INT NOT NULL,
  PRIMARY KEY (`id_account`, `id_Consumer`),
  INDEX `fk_Account_Consumer1_idx` (`id_Consumer` ASC),
  CONSTRAINT `fk_Account_Consumer1`
    FOREIGN KEY (`id_Consumer`)
    REFERENCES `test_pds`.`Consumer` (`id_Consumer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_pds`.`status`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `test_pds`.`status` (
  `id_status` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_pds`.`user`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `test_pds`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `id_Consumer` INT NOT NULL,
  `id_status` INT NOT NULL,
  PRIMARY KEY (`id_user`, `id_Consumer`, `id_status`),
  INDEX `fk_user_Consumer1_idx` (`id_Consumer` ASC),
  INDEX `fk_user_status1_idx` (`id_status` ASC),
  CONSTRAINT `fk_user_Consumer1`
    FOREIGN KEY (`id_Consumer`)
    REFERENCES `test_pds`.`Consumer` (`id_Consumer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_status1`
    FOREIGN KEY (`id_status`)
    REFERENCES `test_pds`.`status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_pds`.`Insurance`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `test_pds`.`Insurance` (
  `id_Insurance` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `rate` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id_Insurance`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_pds`.`refund`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `test_pds`.`refund` (
  `id_refund` INT NOT NULL AUTO_INCREMENT,
  `refund_type` VARCHAR(45) NULL,
  PRIMARY KEY (`id_refund`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_pds`.`LoanType`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `test_pds`.`LoanType` (
  `id_loanType` INT NOT NULL AUTO_INCREMENT,
  `id_Insurance` INT NULL,
  `name` VARCHAR(45) NOT NULL,
  `id_refund` INT NOT NULL,
  `rate` FLOAT NULL,
  PRIMARY KEY (`id_loanType`, `id_Insurance`, `id_refund`),
  INDEX `fk_LoanType_Insurance1_idx` (`id_Insurance` ASC),
  INDEX `fk_LoanType_refund1_idx` (`id_refund` ASC),
  CONSTRAINT `fk_LoanType_Insurance1`
    FOREIGN KEY (`id_Insurance`)
    REFERENCES `test_pds`.`Insurance` (`id_Insurance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LoanType_refund1`
    FOREIGN KEY (`id_refund`)
    REFERENCES `test_pds`.`refund` (`id_refund`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_pds`.`Simulation`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `test_pds`.`Simulation` (
  `id_Simulation` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `simulationDate` DATE NOT NULL,
  `status` INT NOT NULL,
  `duration` BIGINT(20) NOT NULL,
  `amount` INT NOT NULL,
  `interestRate` FLOAT NULL,
  `id_loanType` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Simulation`, `id_user`, `id_loanType`),
  INDEX `fk_Simulation_user1_idx` (`id_user` ASC),
  INDEX `fk_Simulation_LoanType1_idx` (`id_loanType` ASC),
  CONSTRAINT `fk_Simulation_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `test_pds`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Simulation_LoanType1`
    FOREIGN KEY (`id_loanType`)
    REFERENCES `test_pds`.`LoanType` (`id_loanType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_pds`.`loan`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `test_pds`.`loan` (
  `id_loan` INT NOT NULL,
  `id_Simulation` INT NOT NULL,
  PRIMARY KEY (`id_loan`, `id_Simulation`),
  INDEX `fk_loan_Simulation1_idx` (`id_Simulation` ASC),
  CONSTRAINT `fk_loan_Simulation1`
    FOREIGN KEY (`id_Simulation`)
    REFERENCES `test_pds`.`Simulation` (`id_Simulation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_pds`.`Staff`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `test_pds`.`Staff` (
  `id_staff` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_Agency` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NULL,
  `salary` VARCHAR(45) NULL,
  PRIMARY KEY (`id_staff`, `id_user`, `id_Agency`),
  INDEX `fk_Staff_user1_idx` (`id_user` ASC),
  INDEX `fk_Staff_Agency1_idx` (`id_Agency` ASC),
  CONSTRAINT `fk_Staff_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `test_pds`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Staff_Agency1`
    FOREIGN KEY (`id_Agency`)
    REFERENCES `test_pds`.`Agency` (`id_Agency`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_pds`.`history`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `test_pds`.`history` (
  `id_history` INT NOT NULL AUTO_INCREMENT,
  `id_Simulation` INT NOT NULL,
  PRIMARY KEY (`id_history`, `id_Simulation`),
  INDEX `fk_history_Simulation1_idx` (`id_Simulation` ASC),
  CONSTRAINT `fk_history_Simulation1`
    FOREIGN KEY (`id_Simulation`)
    REFERENCES `test_pds`.`Simulation` (`id_Simulation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
