-- MySQL Script generated by MySQL Workbench
-- 03/25/16 20:12:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema test_pds
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `test_pds` ;

-- -----------------------------------------------------
-- Schema test_pds
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test_pds` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `test_pds` ;

-- -----------------------------------------------------
-- Table `test_pds`.`Agency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_pds`.`Agency` ;

CREATE TABLE IF NOT EXISTS `test_pds`.`Agency` (
  `id_Agency` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Agency`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_pds`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_pds`.`user` ;

CREATE TABLE IF NOT EXISTS `test_pds`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_pds`.`Simulation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_pds`.`Simulation` ;

CREATE TABLE IF NOT EXISTS `test_pds`.`Simulation` (
  `id_Simulation` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `monthly` VARCHAR(45) NOT NULL,
  `simulationDate` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `duration` VARCHAR(45) NOT NULL,
  `amount` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Simulation`, `id_user`),
  INDEX `fk_Simulation_user1_idx` (`id_user` ASC),
  CONSTRAINT `fk_Simulation_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `test_pds`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_pds`.`Insurance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_pds`.`Insurance` ;

CREATE TABLE IF NOT EXISTS `test_pds`.`Insurance` (
  `id_Insurance` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `rate` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id_Insurance`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_pds`.`LoanType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_pds`.`LoanType` ;

CREATE TABLE IF NOT EXISTS `test_pds`.`LoanType` (
  `id_loanType` INT NOT NULL AUTO_INCREMENT,
  `id_Insurance` INT NOT NULL,
  PRIMARY KEY (`id_loanType`, `id_Insurance`),
  INDEX `fk_LoanType_Insurance1_idx` (`id_Insurance` ASC),
  CONSTRAINT `fk_LoanType_Insurance1`
    FOREIGN KEY (`id_Insurance`)
    REFERENCES `test_pds`.`Insurance` (`id_Insurance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_pds`.`loan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_pds`.`loan` ;

CREATE TABLE IF NOT EXISTS `test_pds`.`loan` (
  `id_loan` INT NOT NULL AUTO_INCREMENT,
  `id_Simulation` INT NOT NULL,
  `id_loanType` INT NOT NULL,
  PRIMARY KEY (`id_loan`, `id_Simulation`, `id_loanType`),
  INDEX `fk_loan_Simulation1_idx` (`id_Simulation` ASC),
  INDEX `fk_loan_LoanType1_idx` (`id_loanType` ASC),
  CONSTRAINT `fk_loan_Simulation1`
    FOREIGN KEY (`id_Simulation`)
    REFERENCES `test_pds`.`Simulation` (`id_Simulation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_loan_LoanType1`
    FOREIGN KEY (`id_loanType`)
    REFERENCES `test_pds`.`LoanType` (`id_loanType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_pds`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_pds`.`Account` ;

CREATE TABLE IF NOT EXISTS `test_pds`.`Account` (
  `id_account` INT NOT NULL AUTO_INCREMENT,
  `capital` VARCHAR(45) NOT NULL,
  `id_loan` INT NOT NULL,
  PRIMARY KEY (`id_account`, `id_loan`),
  INDEX `fk_Account_loan1_idx` (`id_loan` ASC),
  CONSTRAINT `fk_Account_loan1`
    FOREIGN KEY (`id_loan`)
    REFERENCES `test_pds`.`loan` (`id_loan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_pds`.`Consumer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_pds`.`Consumer` ;

CREATE TABLE IF NOT EXISTS `test_pds`.`Consumer` (
  `id_Consumer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `age` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `postCode` VARCHAR(5) NOT NULL,
  `country` VARCHAR(45) NULL,
  `phoneNumber` VARCHAR(10) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `id_Agency` INT NOT NULL,
  `id_user` INT NOT NULL,
  `id_account` INT NOT NULL,
  PRIMARY KEY (`id_Consumer`, `id_Agency`, `id_user`, `id_account`),
  INDEX `fk_Consumers_Agency1_idx` (`id_Agency` ASC),
  INDEX `fk_Consumers_user1_idx` (`id_user` ASC),
  INDEX `fk_Consumers_Account1_idx` (`id_account` ASC),
  CONSTRAINT `fk_Consumers_Agency1`
    FOREIGN KEY (`id_Agency`)
    REFERENCES `test_pds`.`Agency` (`id_Agency`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consumers_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `test_pds`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consumers_Account1`
    FOREIGN KEY (`id_account`)
    REFERENCES `test_pds`.`Account` (`id_account`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_pds`.`Staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_pds`.`Staff` ;

CREATE TABLE IF NOT EXISTS `test_pds`.`Staff` (
  `id_staff` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_Agency` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NULL,
  `salary` VARCHAR(45) NULL,
  PRIMARY KEY (`id_staff`, `id_user`, `id_Agency`),
  INDEX `fk_Staff_user1_idx` (`id_user` ASC),
  INDEX `fk_Staff_Agency1_idx` (`id_Agency` ASC),
  CONSTRAINT `fk_Staff_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `test_pds`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Staff_Agency1`
    FOREIGN KEY (`id_Agency`)
    REFERENCES `test_pds`.`Agency` (`id_Agency`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_pds`.`Historique`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_pds`.`Historique` ;

CREATE TABLE IF NOT EXISTS `test_pds`.`Historique` (
  `id_Historique` INT NOT NULL AUTO_INCREMENT,
  `id_Simulation` INT NOT NULL,
  PRIMARY KEY (`id_Historique`, `id_Simulation`),
  INDEX `fk_Historique_Simulation1_idx` (`id_Simulation` ASC),
  CONSTRAINT `fk_Historique_Simulation1`
    FOREIGN KEY (`id_Simulation`)
    REFERENCES `test_pds`.`Simulation` (`id_Simulation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
